### ISSUE TITLE
Collapsing a vertices of a FA in a MethodGraph crashes the LayoutAlgorithm

### ISSUE THREAD

**Issue by Lucas-Steinmann** [PSEProgrammgraphen/GraphVonAnsicht#33]
```
Exception in thread "JavaFX Application Thread" java.lang.AssertionError
	at edu.kit.student.joana.methodgraph.MethodGraphLayout.getTurnedEdges(MethodGraphLayout.java:195)
	at edu.kit.student.joana.methodgraph.MethodGraphLayout.drawFieldAccessEdges(MethodGraphLayout.java:124)
	at edu.kit.student.joana.methodgraph.MethodGraphLayout.lambda$0(MethodGraphLayout.java:104)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at edu.kit.student.joana.methodgraph.MethodGraphLayout.layout(MethodGraphLayout.java:104)
	at edu.kit.student.joana.methodgraph.MethodGraphLayout.layout(MethodGraphLayout.java:1)
	at edu.kit.student.joana.methodgraph.MethodGraphLayoutOption.applyLayout(MethodGraphLayoutOption.java:41)
	at edu.kit.student.gui.GraphView$2$1.handle(GraphView.java:243)
	at edu.kit.student.gui.GraphView$2$1.handle(GraphView.java:1)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1405)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$343(ContextMenuContent.java:1358)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:352)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$300(GlassViewEventHandler.java:388)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:387)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$450(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
```

To replicate the issue: 
This should work with every graph containing a FA but for the sake of completeness:
Use [Fields.pdg.graphml.zip](https://github.com/PSEProgrammgraphen/GraphVonAnsicht/files/417079/Fields.pdg.graphml.zip)
Open Graph for function T2().
Select vertices which are part of a FA and collapse them.

Result: 
The stacktrace displayed above will be printed to the console and the graph will not be layoutet.

**Comment by Lucas-Steinmann** [comment]
Due to small changes in layout and model, this bug reappeared.
The reason behind this is probably that FieldAccesses are not sorted out until all vertices in the FieldAccesses are hidden.

**Comment by thatUserjm** [comment]
Fixed as collapsing of vertices from which at least one is in a FieldAccess is not passible anymore
