### ISSUE TITLE
NullpointerException in EdgeDrawer after filtering NORM vertices and relayouting

### ISSUE THREAD

**Issue by thatUserjm** [PSEProgrammgraphen/GraphVonAnsicht#44]
After filtering vertices of kind NORM, pressing Ok and relayouting (choosing MethodGraphLayout) the graph `com.ibm.wala.FakeRootClass.fakeRootMethod()V` in file `SmallControl.pdg.graphml` an NullPoiterException in EdgeDrawer occurs: (commit hash ff7a1c862ecdb13aa8d4187bba3fde80f9a0c60e)

Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at edu.kit.student.sugiyama.steps.EdgeDrawer.getInPoints(EdgeDrawer.java:512)
	at edu.kit.student.sugiyama.steps.EdgeDrawer.fillInOutPoints(EdgeDrawer.java:199)
	at edu.kit.student.sugiyama.steps.EdgeDrawer.drawEdges(EdgeDrawer.java:65)
	at edu.kit.student.sugiyama.SugiyamaLayoutAlgorithm.layout(SugiyamaLayoutAlgorithm.java:142)
	at edu.kit.student.joana.methodgraph.MethodGraphLayout.layout(MethodGraphLayout.java:104)
	at edu.kit.student.joana.methodgraph.MethodGraphLayout.layout(MethodGraphLayout.java:1)
	at edu.kit.student.joana.methodgraph.MethodGraphLayoutOption.applyLayout(MethodGraphLayoutOption.java:41)
	at edu.kit.student.gui.GAnsApplication.openLayoutSettingsDialog(GAnsApplication.java:416)
	at edu.kit.student.gui.GAnsApplication.access$7(GAnsApplication.java:412)
	at edu.kit.student.gui.GAnsApplication$9$1.handle(GAnsApplication.java:491)
	at edu.kit.student.gui.GAnsApplication$9$1.handle(GAnsApplication.java:1)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.event.Event.fireEvent(Unknown Source)
	at javafx.scene.control.MenuItem.fire(Unknown Source)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(Unknown Source)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$343(Unknown Source)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.event.Event.fireEvent(Unknown Source)
	at javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.scene.Scene$MouseHandler.access$1500(Unknown Source)
	at javafx.scene.Scene.impl_processMouseEvent(Unknown Source)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(Unknown Source)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by thatUserjm** [comment]
fixed after last commit.
EdgeDrawer now looks for Isolated vertices
